sudo: required
dist: trusty
language: node_js
node_js:
- 7.7.4
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
install:
  - npm install
before_script:
  - npm install -g firebase-tools
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a ng --version
  - xvfb-run -a npm run ci-test
  - xvfb-run -a npm run ci-e2e
  - xvfb-run -a npm run ci-build
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token "$FIREBASE_TOKEN"
notifications:
  slack: mporium:uG7u8qplkUcLVkenDBgReluv
